name: PermsSystem
description: PermsSystem fo RealityRift by Crasher508
version: 1.0
author: Crasher508
main: dev.crasher508.permssystem.Main
api-version: 1.19
commands:
  pex:
    description: Permission command
    usage: /pex <user|group|setdefaultgroup|help> <value>
permissions:
  pex.command:
    default: op